version: "3.9"
services:
  db:
    image: postgres:15.3-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123123123
      POSTGRES_DB: salespot
    ports:
      - "15432:5432"

  redis-db:
    image: redis:7.0.5-alpine
    ports:
      - "16379:6379"

  consul:
    image: consul:1.15
    ports:
      - 8500:8500

  product_service:
    build:
      dockerfile: ./services/product_service/Dockerfile.dev
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
    environment:
      DB_DSN: ${DB_DSN}
      CONSUL_HOST: consul:8500
      REDIS_URI: redis://redis-db:6379
    ports:
      - 13000:3000

